Use $ as jQuery.noConflict
Thanks for awesome FormBuilder
jQuery will conflict "Uncaught TypeError: $ is not a function" when use in Joomla!.

My simple idea just define a local $ = jQuery.noConflict();